#!%(installation.prereqs.python)s
# -*- mode: python -*-

import sys
import argparse
import os
import pwd
import grp

# To avoid accidentally creating files owned by root.
sys.dont_write_bytecode = True

system_user_uid = pwd.getpwnam("%(installation.system.username)s").pw_uid
system_user_gid = grp.getgrnam("%(installation.system.groupname)s").gr_gid

try:
    os.setegid(system_user_gid)
    os.seteuid(system_user_uid)
except OSError:
    print >>sys.stderr, "ERROR: Failed to set UID = %(installation.system.username)s. Run as root?"
    sys.exit(1)

argv = sys.argv[1:]

global_argv = []
command = None
command_argv = []

parser = argparse.ArgumentParser(
    description="Critic administration interface",
    usage="%%(prog)s [-h] [--etc-dir ETC_DIR] [--identify IDENTITY] COMMAND [options]",
    add_help=False)

parser.add_argument("--help", "-h", action="store_true",
                    help="show this help message and exit")
parser.add_argument("--etc-dir", "-e", default="%(installation.paths.etc_dir)s",
                    help="Critic configuration directory [default=%(installation.paths.etc_dir)s]")
parser.add_argument("--identity", "-i", default="main",
                    help="system identity to manage [default=main]")

while argv:
    argument = argv[0]
    if argument in ("--help", "-h"):
        global_argv.append(argument)
        del argv[0]
        continue
    elif argument in ("--etc-dir", "-e",
                      "--identity", "-i"):
        global_argv.extend(argv[:2])
        del argv[:2]
        continue
    elif argument.startswith("--etc-dir=") \
            or argument.startswith("-e") \
            or argument.startswith("--identity=") \
            or argument.startswith("-i"):
        global_argv.append(argument)
        del argv[0]
        continue
    elif argument.startswith("-"):
        # Invalid argument; add it to global_argv so that parser.parse_args()
        # below fails.
        global_argv.append(argument)

    break

if argv:
    command = argv[0]
    command_argv = argv[1:]

arguments = parser.parse_args(global_argv)

etc_path = os.path.join(arguments.etc_dir, arguments.identity)

class Error(Exception):
    pass

try:
    if not os.access(arguments.etc_dir, os.R_OK | os.X_OK):
        raise Error("Directory is inaccessible: %%s" %% arguments.etc_dir)

    if not os.path.isdir(etc_path):
        raise Error("Invalid identity: %%s" %% arguments.identity)

    sys.path.insert(0, etc_path)

    try:
        import configuration
    except ImportError:
        raise Error("Failed to import: configuration")

    sys.path.insert(1, configuration.paths.INSTALL_DIR)
    sys.path.insert(2, configuration.paths.DATA_DIR)

    try:
        import maintenance.criticctl
    except ImportError:
        raise Error("Failed to import: maintenance.criticctl")

    sys.exit(maintenance.criticctl.main(parser, arguments.help,
                                        command, command_argv))
except Error as error:
    if arguments.help:
        parser.print_help()
        print

    print >>sys.stderr, "ERROR: %%s" %% error.message
    sys.exit(1)
