<VirtualHost *:80>
	ServerAdmin %(installation.admin.email)s
	ServerName %(installation.system.hostname)s

	WSGIApplicationGroup %%{GLOBAL}
	WSGIProcessGroup critic-main
	WSGIDaemonProcess critic-main processes=2 \
	                              threads=25 \
	                              home=%(installation.paths.install_dir)s \
	                              python-path=%(installation.paths.etc_dir)s/main:%(installation.paths.install_dir)s \
	                              user=%(installation.system.username)s \
	                              group=%(installation.system.groupname)s

	WSGIImportScript %(installation.paths.install_dir)s/wsgistartup.py \
	                 process-group=critic-main \
	                 application-group=%%{GLOBAL}

	WSGIScriptAlias / %(installation.paths.install_dir)s/wsgi.py

        WSGIPassAuthorization %(installation.apache.pass_auth)s

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	ErrorLog %(installation.paths.log_dir)s/main/error.log
	CustomLog %(installation.paths.log_dir)s/main/access.log combined

	Alias /static-resource/ "%(installation.paths.install_dir)s/resources/"
	<Directory "%(installation.paths.install_dir)s/resources">
		Options FollowSymLinks
		AllowOverride None
		Order allow,deny
		Allow from all
		ExpiresActive On
		ExpiresDefault A2592000
	</Directory>
</VirtualHost>
