/* Generated by ui/src/extensions/generate.py. DO NOT MODIFY! */

import React, { useEffect, useState } from "react"

import { WithCritic } from "../extension"

const Extensions = () => {
  const [EmailDelivery, setEmailDelivery] = useState<
    React.FunctionComponent<{}>
  >(() => () => null)

  useEffect(() => {
    import(
      /* webpackChunkName: "EmailDelivery" */ "./EmailDelivery"
    ).then((module) => setEmailDelivery(() => module.default))
  })

  return (
    <>
      <WithCritic extensionKey="EmailDelivery">
        <EmailDelivery />
      </WithCritic>
    </>
  )
}

export default Extensions
