FROM nginx

WORKDIR /critic

COPY ui/build/static static
COPY dockerfiles/nginx/site.template site.template

CMD envsubst < site.template > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"
