[uwsgi]
master = true

# Use a shared socket to allow binding to a privileged port without running as
# root.
shared-socket = :80
http = =0

# Redirect to the Critic backend.
http-to = %(installation.paths.run_dir)s/main/sockets/uwsgi.unix

# Run as the "web server" user/group.
uid = %(installation.httpd.username)s
gid = %(installation.httpd.groupname)s
