server {
	listen 80;
	listen [::]:80;

	server_name %(installation.system.hostname)s;

	location / {
		uwsgi_pass unix://%(installation.paths.run_dir)s/main/sockets/uwsgi.unix;
		include uwsgi_params;
	}

	location /static-resource/ {
		alias %(installation.paths.install_dir)s/resources/;
		expires 30d;

		types {
			text/css css;
			text/javascript js;
			image/png png;
		}
	}
}
